config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
    resources :lists
  end
  
  resources :movies
  
  root 'movies#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    validates :name, presence: true
    validates :description, length: { maximum: 250 }

    belongs_to :user
    
    has_many :selections
    has_many :movies, through: :selections
    accepts_nested_attributes_for :movies

    def movies_attributers=(mvoies_attributes)
        movies_attributes.values.each do |movie_attribute|
            movie = Movie.find_or_create_by(movie_attribute)
            self.movies << movie
        end
    end
end

app/models/movie.rb
class Movie < ApplicationRecord
    validates :title, uniqueness: true
    validates :title, presence: true
    validates :synopsis, presence: true
    validates :mpaa_rating, presence: true

    has_many :selections
    has_many :lists, through: :selection
end

app/models/selection.rb
class Selection < ApplicationRecord
    belongs_to :list
    belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord

  has_many :lists

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    before_action :set_list, only: [:edit, :update, :destroy]
    before_action :security_check, only: [:edit, :update, :destroy]
    before_action :set_user, only: [:index, :show]
    before_action :set_current_user, only: [:new, :create, :edit, :update, :destroy]

    def index
        @lists = List.all
    end

    def show
        @list = @user.lists.find(params[:id])
    end

    def new
        @list = @user.lists.build
    end

    def create
        @list = @user.lists.build(list_params)
        @list.user_id = current_user.id

        if @list.save
            redirect_to user_list_path(@user,@list)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        @list.update(list_params)

        if @list.save
            redirect_to user_list_path(@user,@list)
        else
            render 'edit'
        end
    end

    def destroy
        @list.destroy
        redirect_to user_lists_path
    end

    private

    def list_params
        params.require(:list).permit(:name, :description, :user_id, movie_ids: [], movies_attributes: [:title, :synopsis, :mpaa_rating])
    end

    def set_list
        @list = List.find(params[:id])
    end

    def set_current_user
        @user = current_user
    end

    def set_user
        @user = User.find(params[:user_id])
    end

    def security_check
        if user_signed_in?
            if current_user.id != @list.user_id
                redirect_to root_path
            end
        end
    end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    before_action :set_movie, only: [:show, :edit, :update, :destroy]

    def index
        @movies = Movie.all
        @lists = List.all
        @user = User.find_by_id(params[:user_id])
    end

    def show
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)
        @movie.user_id = current_user.id

        if @movie.save
            redirect_to movie_path(@movie)
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        @movie.update(movie_params)
        
        if @movie.save
            redirect_to movie_path(@movie)
        else
            render 'new'
        end
    end

    def destroy
        @movie.destroy
        redirect_to root_path
    end

    private
    def movie_params
        params.require(:movie).permit(:title, :synopsis, :mpaa_rating, :release_date)
    end

    def set_movie
        @movie = Movie.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <% if user_signed_in? %>

            <li class="nav-item">
                <%= link_to "New Movie", new_movie_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to "New List", new_user_list_path(current_user), class: "nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to "My Lists", user_lists_path(current_user), class: "nav-link" %>
            </li>

        <% end %>

    </ul>
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>

            <li class="nav-item">
                <!--
                 Need to make a user page and link to it
                 Add username field to devise model
                 Maybe dropdown for individual settings pages?
                 -->
                <a href="#" class="nav-link"><%= current_user.email %></a>
            </li>

            <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, class: "nav-link" %>
            </li>
        <% else %>

            <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class: "nav-link"%>
            </li>

            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
            </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jfdb</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    <div>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>    
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_for [:user, @list] do |f| %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.collection_select(:movie_ids, Movie.all, :id, :title, { include_blank: true }) %>
    </div>

    <div class="form-group">
        <%= f.fields_for :movies, @list.movies.build do |movie_fields| %>

            <div class="form-group">
                <%= movie_fields.label :title %>
                <%= movie_fields.text_field :title, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= movie_fields.label :synopsis %>
                <%= movie_fields.text_area :synopsis, class: "form-control" %>
            </div>

            <div class="form-group">
                <%= movie_fields.label :mpaa_rating %>
                <%= select(:movie, :mpaa_rating, options_for_select([ 'G', 'PG', 'PG-13', 'R' ]), { include_blank: true }) %>
            </div>

            <div class="form-group">
                <%= movie_fields.label :release_date %>
                <%= date_select("movie", "release_date", start_year: 1900, order: [:day, :month, :year])%>
            </div>
        <% end %>
    </div>

    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/lists/edit.html.erb
<div class="container">
    <h1>Edit List</h1>
</div>
<%= render 'form' %>

app/views/lists/index.html.erb
<h1>Lists</h1>
<ul class="list-group">
    <% @lists.each do |list| %>
        <li class="list-group-item"><%= link_to list.name, user_list_path(@user.id, list) %></li>
    <% end %>
</ul>

app/views/lists/new.html.erb
<div class="container">
    <h1>New List</h1>
</div>
<%= render 'form', user: @user %>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<p><%= @list.description %></p>

<% if user_signed_in? %>
    <% if current_user.id == @list.user_id %>
        <%= link_to "Edit", edit_user_list_path(@list) %>
        <%= link_to "Delete", user_list_path(@list), method: :delete %>
    <% end %>
<% end %>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
    </div>
    
    <div class="form-group">
        <%= f.label :synopsis %>
        <%= f.text_area :synopsis, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :mpaa_rating %>
        <%= select(:movie, :mpaa_rating, options_for_select([ 'G', 'PG', 'PG-13', 'R' ]), { include_blank: true }) %>
    </div>

    <div class="form-group">
        <%= f.label :release_date %>
        <%= date_select("movie", "release_date", start_year: 1900, order: [:day, :month, :year])%>
    </div>

    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/movies/edit.html.erb
<div class="container">
    <h1>Edit Movie</h1>
</div>
<%= render 'form' %>

app/views/movies/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Movies</h1>

            <ul class="list-group">
                <% @movies.each do |movie| %>
                    <li class="list-group-item"><%= link_to movie.title, movie_path(movie) %></li>
                <% end %>
            </ul>

        </div>
        <div class="col">
            <h1>Lists</h1>
            
            <ul class="list-group">
                <% @lists.each do |list| %>
                    <li class="list-group-item"><%= link_to list.name, user_list_path(list.user_id, list) %></li>
                <% end %>
            </ul>
        </div>
    </div>
</div>

app/views/movies/new.html.erb
<div class="container">
    <h1>New Movie</h1>
</div>
<%= render 'form' %>

app/views/movies/show.html.erb
<h1><%= @movie.title %></h1>
<p><%= @movie.synopsis %></p>
<p><%= @movie.mpaa_rating %></p>
<p><%= @movie.release_date.strftime('%B %d, %Y') %></p>

<%= link_to "Edit", edit_movie_path(@movie) %>
<%= link_to "Delete", movie_path(@movie), method: :delete %>